spring:
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${APPOINTMENT_DB_USERNAME}
        password: ${APPOINTMENT_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration
        user: ${APPOINTMENT_DB_USERNAME}
        password: ${APPOINTMENT_DB_PASSWORD}
        baseline-version: ${FLYWAY_BASELINE_VERSION}
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: appointmentCreated:com.patientapp.appointmentservice.modules.notification.AppointmentCreatedRequest
server:
    port: ${APPOINTMENT_SERVER_PORT}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH}

application:
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
    config:
        auth-url: ${AUTH_SERVICE_URL}
        doctor-url: ${DOCTOR_SERVICE_URL}
        patient-url: ${PATIENT_SERVICE_URL}