spring:
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${AUTH_DB_USERNAME}
        password: ${AUTH_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration
        user: ${AUTH_DB_USERNAME}
        password: ${AUTH_DB_PASSWORD}
        baseline-version: ${FLYWAY_BASELINE_VERSION}
server:
    port: ${AUTH_SERVER_PORT}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH}
application:
    front-end:
        url: ${FRONT_END_URL}
        domain: ${FRONT_END_DOMAIN}
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
            expiration: ${JWT_EXPIRATION}
            refresh-token:
                expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}