spring:
    cloud:
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: true
                    routes:
                        # Endpoints normales de auth
                        -   id: auth-service
                            uri: lb:http://AUTH-SERVICE
                            predicates:
                                - Path=/api/v1/auth/**

                        - id: auth-service-csrf
                          uri: lb:http://AUTH-SERVICE
                          predicates:
                            - Path=/api/v1/csrf/**

                        # Inicio de OAuth2
                        -   id: auth-service-oauth-start
                            uri: lb:http://AUTH-SERVICE
                            predicates:
                                - Path=/api/v1/oauth2/authorization/**

                        # Callback de OAuth2
                        -   id: auth-service-oauth-callback
                            uri: lb:http://AUTH-SERVICE
                            predicates:
                                - Path=/login/oauth2/code/**

                        # Endpoints normales de doctor
                        -   id: doctor-service
                            uri: lb:http://DOCTOR-SERVICE
                            predicates:
                                - Path=/api/v1/doctors/**

                        # Endpoints normales de patient
                        -   id: patient-service
                            uri: lb:http://PATIENT-SERVICE
                            predicates:
                                - Path=/api/v1/patients/**
server:
    port: ${GATEWAY_SERVER_PORT}

application:
    front-end:
        url: ${FRONT_END_URL}
        domain: ${FRONT_END_DOMAIN}